{
 "title": "Save Your Money",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "type",
    "label": "Type",
    "query": "select distinct(_type) from budget"
   },
   {
    "name": "method",
    "label": "Method",
    "query": "select distinct(method) from budget;"
   },
   {
    "name": "category",
    "label": "Category",
    "query": "select distinct(category) from budget;"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Income",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(value) from sym.budget where _type=\"income\" and $__timeFilter(date) and category in ($category) and method in ($method);"
    }
   ]
  },
  {
   "title": "balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 14, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  (select sum(value) from sym.budget where $__timeFilter(date) and _type=\"income\" and category in ($category) and method in ($method))- \n  (select sum(value) from sym.budget where $__timeFilter(date) and _type=\"expense\" and category in ($category) and method in ($method)) as balance;"
    }
   ]
  },
  {
   "title": "Total Expense",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(value) from sym.budget where _type=\"expense\" and $__timeFilter(date) and category in ($category) and method in ($method);"
    }
   ]
  },
  { "title": "Expense", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Expense timeline ( by month )",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 5 },
   "targets": [
    {
     "dataset": "sym",
     "rawSql": "SELECT method,_type,sum(value),DATE_FORMAT(date, '%Y-%m-%d') as date FROM sym.budget where $__timeFilter(date) and category in ($category) and _type = 'expense' and method in ($method) group by MONTH(date),YEAR(date);"
    }
   ]
  },
  {
   "title": "Expense timeline ( by day )",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 5 },
   "targets": [
    {
     "dataset": "sym",
     "rawSql": "SELECT method,_type,sum(value),DATE_FORMAT(date, '%Y-%m-%d') as date FROM sym.budget where $__timeFilter(date) and category in ($category) and _type = 'expense' and method in ($method) group by date;"
    }
   ]
  },
  {
   "title": "Expense timeline ( by value )",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 5 },
   "targets": [
    {
     "dataset": "sym",
     "rawSql": "SELECT name,category,method,_type,value,DATE_FORMAT(date, '%Y-%m-%d') as date FROM sym.budget where $__timeFilter(date) and category in ($category) and _type = 'expense' and method in ($method);"
    }
   ]
  },
  {
   "title": "Total Expense(  by category )",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select category, sum(value) from budget where $__timeFilter(date) and _type=\"expense\" group by category;"
    }
   ]
  },
  {
   "title": "Expense details",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 13 },
   "targets": [
    {
     "rawSql": "select name, category, method, _type, DATE_FORMAT(date, '%Y-%m-%d') as date, value from sym.budget where $__timeFilter(date) and category in ($category) and _type = 'expense' and method in ($method);"
    }
   ]
  },
  { "title": "Income", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Income timeline ( by day )",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "sym",
     "rawSql": "SELECT name,category,method,_type,sum(value),DATE_FORMAT(date, '%Y-%m-%d') as date FROM sym.budget where $__timeFilter(date) and category in ($category) and _type = 'income' and method in ($method) GROUP BY MONTH(date),YEAR(date), _type"
    }
   ]
  },
  {
   "title": "Income timeline ( by day )",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 24 },
   "targets": [
    {
     "dataset": "sym",
     "rawSql": "SELECT name,category,method,_type,sum(value),DATE_FORMAT(date, '%Y-%m-%d') as date FROM sym.budget where $__timeFilter(date) and category in ($category) and _type = 'income' and method in ($method) GROUP BY date, _type"
    }
   ]
  },
  {
   "title": "Income timeline ( by value )",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 24 },
   "targets": [
    {
     "dataset": "sym",
     "rawSql": "SELECT name,category,method,_type,value,DATE_FORMAT(date, '%Y-%m-%d') as date FROM sym.budget where $__timeFilter(date) and category in ($category) and _type = 'income' and method in ($method);"
    }
   ]
  },
  {
   "title": "Total Income ( by category )",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select category, sum(value) from budget where $__timeFilter(date) and _type=\"income\" group by category;"
    }
   ]
  },
  {
   "title": "Income details",
   "type": "table",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 32 },
   "targets": [
    {
     "rawSql": "select name, category, method, _type, DATE_FORMAT(date, '%Y-%m-%d') as date, value from sym.budget where $__timeFilter(date) and category in ($category) and _type = 'income' and method in ($method);"
    }
   ]
  }
 ]
}